### ISSUE TITLE
Rotary Encoder with Knob

### ISSUE THREAD

**Issue by jarangmandi** [adafruit/Fritzing-Library#13]
Connectors on PCB and Breadboard views don't match with that on Schematic view. Encoder "B" and "COM" are swapped over.

**Comment by daspuru** [comment]
Hi this problem persists!

Hi! The Fritzing object for the Rotary Encoder (https://www.adafruit.com/product/377) is wrong, the pins do not correspond to the schematic. The center pin which must be ground is inverter with one signal pin. I sent to manufacture some boards and there are wrong because of that issue. I hope you can notify if you received this. Thanks a lot!
